server:
  port: 8090
  forward-headers-strategy: framework
  compression:
    enabled: true
  error:
    whitelabel:
        enabled: false
spring:
  output:
    ansi:
      enabled: detect
  r2dbc:
    url: r2dbc:pool:mysql://47.99.49.255:3307/blog
    username: blog
    password: hb742608.
  sql:
    init:
      mode: always
      platform: mysql
  codec:
    max-in-memory-size: 10MB
  messages:
    basename: config.i18n.messages
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d

halo:
  work-dir: ${user.home}/.halo2
  plugin:
    plugins-root: ${halo.work-dir}/plugins
  attachment:
    resource-mappings:
      - pathPattern: /upload/**
        locations:
          - migrate-from-1.x

springdoc:
  api-docs:
    enabled: false
  writer-with-order-by-keys: true

logging:
  file:
    name: ${halo.work-dir}/logs/halo.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 0

management:
  endpoints:
    web:
      exposure:
          include: ["health", "info", "startup", "globalinfo", "logfile"]
  endpoint:
    health:
      probes:
        enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
